### ISSUE TITLE
Wrong permission

### ISSUE THREAD

**Issue by VintageGnu** [Throneos/PortableMending#1]
PortableMending 1.0.0
LuckPerms 5.3.64

Adding the "portableMend.mend" permission didn't allow the use of the mend command (but adding just "mend" does), I believe this is because in src/main/resources/plugin.yml you have "mend" as the command permission instead of "portableMend.mend".

**Comment by deniz-frick** [comment]
Thank you very much!
I just tested it that was in fact the issue.
I also took the chance to make the config naming a little less confusing.

Expect a release in a few minutes.
